name       : qt4
version    : 4.8.7
release    : 3
homepage   : http://www.qt.io/
source     :
    - http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz : e2882295097e47fe089f8ac741a95fef47e0a73a3f3cdf21b56990638f626ea0
license    : LGPL-2.1
summary    : A cross-platform application and UI framework
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libdrm)
    - pkgconfig(libpulse)
    - pkgconfig(libtiff-4)
    - pkgconfig(nss)
    - pkgconfig(pango)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xext)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xv)
    - pkgconfig(zlib)
    - gperf
    - libjpeg-turbo-devel
description: |
   	A cross-platform application and UI framework
patterns   :
    - devel: /usr/bin/qmake
setup      : |
    unset LD_AS_NEEDED
    ./configure --prefix=/usr --libdir=/usr/lib64 -bindir /usr/bin -datadir /usr/share/qt4 -docdir /usr/share/doc/qt4 -sysconfdir /etc/xdg -plugindir %libdir%/qt4/plugins -translationdir /usr/share/qt4/translations -importdir %libdir%/qt4/imports -headerdir /usr/include/qt4 \
        -dbus-linked \
        -graphicssystem raster \
        -opensource -confirm-license \
        -no-phonon -no-phonon-backend \
        -no-webkit \
        -nomake demos -nomake docs -nomake examples \
        -no-openvg \
        -no-reduce-relocations \
        -no-rpath \
        -opengl \
        -openssl-linked \
        -optimized-qmake
build      : |
    unset LD_AS_NEEDED
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$srcdir/lib"
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install INSTALL_ROOT=$installdir
    pushd $installdir/usr/bin
    for i in *; do
      mv "$i" "${i}-qt4"
    done
    popd
