name       : qt4
version    : 4.8.7
release    : 17
homepage   : http://www.qt.io/
source     :
    - http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz : e2882295097e47fe089f8ac741a95fef47e0a73a3f3cdf21b56990638f626ea0
license    : LGPL-2.1
summary    : A cross-platform application and UI framework
component  : desktop.qt
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libdrm)
    - pkgconfig(libpulse)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(nss)
    - pkgconfig(pango)
    - pkgconfig(sqlite3)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xext)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xv)
    - gperf
description: |
    A cross-platform application and UI framework
patterns   :
    - devel : /usr/bin/qmake
setup      : |
    %patch -p1 < $pkgfiles/qt-everywhere-opensource-src-4.8.7-gcc6.patch
    %patch -p1 < $pkgfiles/0001-Enable-building-with-C-11-and-C-14.patch
    %patch -p1 < $pkgfiles/0001-qapplication-x11-Detect-the-MATE-desktop-as-GNOME.patch
    %patch -p1 < $pkgfiles/qt-everywhere-opensource-src-4.8.7-icu59.patch
    unset LD_AS_NEEDED
    export CXXFLAGS="$CXXFLAGS -std=gnu++98 -Wno-deprecated"
    ./configure --prefix=/usr --libdir=/usr/lib64 -bindir /usr/bin -datadir /usr/share/qt4 -docdir /usr/share/doc/qt4 -sysconfdir /etc/xdg -plugindir %libdir%/qt4/plugins -translationdir /usr/share/qt4/translations -importdir %libdir%/qt4/imports -headerdir /usr/include/qt4 \
        -dbus-linked \
        -graphicssystem raster \
        -opensource -confirm-license \
        -no-phonon -no-phonon-backend \
        -no-webkit \
        -nomake demos -nomake docs -nomake examples \
        -no-openvg \
        -no-reduce-relocations \
        -no-rpath \
        -opengl \
        -openssl-linked \
        -optimized-qmake \
        -plugin-sql-sqlite \
        -system-sqlite
build      : |
    unset LD_AS_NEEDED
    export CXXFLAGS="$CXXFLAGS -std=gnu++98 -Wno-deprecated"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$workdir/lib"
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install INSTALL_ROOT=$installdir
    pushd $installdir/usr/bin
    for i in *; do
      mv "$i" "${i}-qt4"
    done
    popd
